import { Link } from "react-router-dom";
import { Dumbbell, Sparkles, TrendingUp, Brain, ArrowRight } from "lucide-react";
import heroImage from "../assets/hero-fitness.jpg";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { useAuth } from "../context/AuthContext";

const Home = () => {
  const { user, loading } = useAuth();

  // Prevent flicker while Firebase checks auth
  if (loading) return null;

  const features = [
    {
      icon: Brain,
      title: "AI-Powered Plans",
      description:
        "Get personalized workout and diet plans generated by advanced AI models tailored to your goals.",
    },
    {
      icon: TrendingUp,
      title: "Track Progress",
      description:
        "Monitor your fitness journey with detailed analytics and visual progress charts.",
    },
    {
      icon: Sparkles,
      title: "Smart Adaptation",
      description:
        "Your plans evolve as you progress, ensuring continuous improvement and results.",
    },
  ];

  return (
    <div className="min-h-screen bg-background">
      <Navbar />

      {/* HERO SECTION */}
      <section className="relative min-h-screen flex items-center overflow-hidden">
        <div className="absolute inset-0">
          <img
            src={heroImage}
            alt="Fitness"
            className="w-full h-full object-cover opacity-40"
          />
          <div className="absolute inset-0 bg-gradient-to-r from-background via-background/90 to-background/60" />
          <div className="absolute inset-0 bg-gradient-to-t from-background via-transparent to-transparent" />
        </div>

        <div className="container relative mx-auto px-4 pt-24">
          <div className="max-w-2xl">
            <div className="inline-flex items-center gap-2 rounded-full bg-primary/10 border border-primary/20 px-4 py-1.5 mb-6">
              <Sparkles className="h-4 w-4 text-primary" />
              <span className="text-sm font-medium text-primary">
                AI-Powered Fitness
              </span>
            </div>

            <h1 className="text-5xl md:text-7xl font-display font-bold text-foreground leading-tight mb-6">
              Your Personal
              <br />
              <span className="text-gradient">AI Trainer</span>
            </h1>

            <p className="text-lg text-muted-foreground max-w-lg mb-8">
              Transform your fitness journey with AI-generated workout and diet
              plans, personalized to your body and goals.
            </p>

            {/* CONDITIONAL BUTTONS */}
            <div className="flex flex-col sm:flex-row gap-4">
              {user ? (
                <Link
                  to="/dashboard"
                  className="inline-flex items-center justify-center gap-2 rounded-lg gradient-primary px-8 py-4 font-semibold text-primary-foreground hover:opacity-90 transition-all glow-primary text-lg"
                >
                  Go to Dashboard
                  <ArrowRight className="h-5 w-5" />
                </Link>
              ) : (
                <>
                  <Link
                    to="/signup"
                    className="inline-flex items-center justify-center gap-2 rounded-lg gradient-primary px-8 py-4 font-semibold text-primary-foreground hover:opacity-90 transition-all glow-primary text-lg"
                  >
                    Get Started Free
                    <ArrowRight className="h-5 w-5" />
                  </Link>

                  <Link
                    to="/login"
                    className="inline-flex items-center justify-center gap-2 rounded-lg border border-border px-8 py-4 font-semibold text-foreground hover:bg-secondary transition-all text-lg"
                  >
                    Login
                  </Link>
                </>
              )}
            </div>
          </div>
        </div>
      </section>

      {/* FEATURES */}
      <section className="py-24 bg-surface">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-display font-bold text-foreground mb-4">
              Why <span className="text-gradient">Vita-Train AI</span>?
            </h2>
            <p className="text-muted-foreground max-w-md mx-auto">
              Cutting-edge AI technology meets fitness science.
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8 max-w-4xl mx-auto">
            {features.map((feature) => (
              <div
                key={feature.title}
                className="glass-card p-8 text-center hover:border-primary/30 transition-all"
              >
                <div className="inline-flex items-center justify-center h-14 w-14 rounded-xl bg-primary/10 mb-6">
                  <feature.icon className="h-7 w-7 text-primary" />
                </div>
                <h3 className="text-xl font-display font-semibold text-foreground mb-3">
                  {feature.title}
                </h3>
                <p className="text-muted-foreground text-sm">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24">
        <div className="container mx-auto px-4 text-center">
          <div className="glass-card max-w-2xl mx-auto p-12">
            <Dumbbell className="h-12 w-12 text-primary mx-auto mb-6" />
            <h2 className="text-3xl font-display font-bold text-foreground mb-4">
              Ready to Transform?
            </h2>
            <p className="text-muted-foreground mb-8">
              Join Vita-Train AI and start your AI-powered fitness journey today.
            </p>

            <Link
              to={user ? "/dashboard" : "/signup"}
              className="inline-flex items-center justify-center gap-2 rounded-lg gradient-primary px-8 py-4 font-semibold text-primary-foreground hover:opacity-90 transition-all glow-primary"
            >
              {user ? "Go to Dashboard" : "Start Now — It's Free"}
              <ArrowRight className="h-5 w-5" />
            </Link>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default Home;